blog/urls.py
from django.urls import path
from blog.feeds import LatestPostsFeed

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('detail/<slug:post>/<int:year>/<int:month>/<int:day>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('search/', views.post_search, name='post_search'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

mysite/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from blog.sitemaps import PostSitemap


sitemaps = {'posts': PostSitemap}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib,sitemaps.views.sitemap'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    """New manager for filtering published posts."""

    def get_queryset(self):
        """Method will be executed every Post.published.all() [example]"""
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    """Model for posts."""
    STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'),)
    title = models.CharField(max_length=225)
    slug = models.SlugField(max_length=225, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    objects = models.Manager()  # Save objects manager as default
    published = PublishedManager()  # Add custom manager
    tags = TaggableManager()

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
        ordering = ('-publish',)

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug, self.publish.year, self.publish.month, self.publish.day])

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=225)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'
        ordering = ('created',)

    def __str__(self):
        return 'Comment on {}, by {}'.format(self.post, self.name)

blog/forms.py
from django import forms
from . import models


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=225)
    email = forms.EmailField()
    to = forms.EmailField()
    comment = forms.CharField(required=False, widget=forms.Textarea)  # widget - type of HTML element


class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ('name', 'email', 'body',)


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from django.db.models import Count
from django.views.generic import ListView
from taggit.models import Tag

from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm


# Create your views here.
def post_list(request, tag_slug=None):
    object_list = Post.published.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 1)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag})


# class PostListView(ListView):
#     queryset = Post.published.all()
#     paginate_by = 1
#     template_name = 'blog/post/list.html'
#     context_object_name = 'posts'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, status='published', publish__year=year, publish__month=month, publish__day=day,
                             slug=post)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)  # create object, but not save into db
            new_comment.post = post
            new_comment.save()
    else:
        form = CommentForm()

    post_tags_ids = post.tags.all().values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request, 'blog/post/detail.html',
                  {'object': post, 'form': form, 'comments': comments, 'new_comment': new_comment,
                   'similar_posts': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data  # dictionary with keys - name field, values - values
            post_url = request.build_absolute_uri(post.get_absolute_url())  # create full post link for sending by email
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comment'])
            send_mail(subject, message, 'shopmanage7@gmail.com', [cd['to']], False)
            sent = True  # flag for complete message in template
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
    search_query = SearchQuery(query)
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        print('a')
    if form.is_valid():
        query = form.cleaned_data['query']
        print(query)
        results = Post.objects.annotate(similarity=TrigramSimilarity('title', query),).filter(
            similarity__gt=0.3).order_by('-similarity')

    return render(request, 'blog/post/search.html', {'form': form, 'query': query, 'results': results})

blog/templates/blog/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
<div id="sidebar">
    <h2>My blog</h2>
    <p>This is my blog. I`ve written {% total_posts %} posts so far.</p>

<p><a href="{% url 'blog:post_feed' %}">Subscribe to my RSS!</a> </p>

    <h3>Latest posts:</h3>
    {#      custom inclusive tag#}
    {% show_latest_posts 3 %}

    <h3>Most commented posts:</h3>
    {# must have! #}
    {% total_comments as total_comments %}
    <ul>
        {% for com_post in total_comments %}
            <li><a href="{{ com_post.get_absolute_url }}">{{ com_post.title }}</a></li>
        {% endfor %}
    </ul>
</div>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% load blog_tags %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
    <h1>{{ object.title }}</h1>

    <p class="date">
        Published {{ object.publish }} by {{ object.author }}
    </p>
    {{ object.body|markdown }}  <!-- linebreaks - = /n -->
    <p>
        <a href="{% url "blog:post_share" object.id %}">
            Share this post
        </a>
    </p>

    <h2>Similar posts</h2>
  {% for post in similar_posts %}
    <p>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
  {% empty %}
    There are no similar posts yet.
  {% endfor %}

    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Your comment has been added!</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" value="Comment!"></p>
        </form>
    {% endif %}


{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% load blog_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}
    <h1>My Blog</h1>

    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}

    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="tags">
            Tags:
            {% for tag in post.tags.all %}

                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                {% if not forloop.last %},{% else %}.{% endif %}

            {% endfor %}

        </p>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords_html:30}}
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}

{% block title %}
    Search
{% endblock title %}


{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
        {% with results.count as total_results %}
            Found {{ total_results }} result {{ total_results|pluralize }}
        {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            {{ post.body|truncatewords:5 }}
        {% empty %}
            <p>There is no results for your query.</p>
        {% endfor %}
        <p><a href="{% url 'blog:post_search' %}">Search again</a> </p>
    {% else %}
        <h1>Search for posts:</h1>
        <form action="." method="get">
            {{ form.as_p }}
        <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock content %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form action="." method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
      {% endif %}
  </span>
</div>